version: '3.8'

services:
  wekandb:
    image: mongo:6
    container_name: wekan-db
    restart: always
    command: mongod --logpath /dev/null --oplogSize 128 --replSet rs0 --quiet
    networks:
      - wekan-network
    expose:
      - 27017
    volumes:
      - wekan-db:/data/db
      - wekan-db-dump:/dump

  wekandb-init:
    image: mongo:6
    container_name: wekan-db-init
    depends_on:
      - wekandb
    networks:
      - wekan-network
    restart: "no"
    entrypoint: [ "sh", "-c", "sleep 5 && mongosh --host wekandb --eval 'rs.initiate()'" ]

  wekan:
    image: adamray67/wekan-app:latest
    container_name: wekan-app
    restart: always
    depends_on:
      - wekandb-init
    ports:
      - "3000:8080"
    environment:
      - BASE_SORT_URL=http://ai-cards-sort:5001
      - MONGO_URL=mongodb://wekandb:27017/wekan
      - MONGO_OPLOG_URL=mongodb://wekandb:27017/local?replicaSet=rs0
      - WITH_API=true
    networks:
      - wekan-network
    volumes:
      - wekan-storage:/wekan_storage

  ai_sorting:
    image: adamray67/ai-cards-sort:latest
    container_name: ai-cards-sort
    restart: always
    depends_on:
      - wekan
    environment:
      - BASE_URL=http://wekan:8080
    networks:
      - wekan-network

  tests:
    image: adamray67/wekan-tests:latest
    container_name: wekan-tests
    depends_on:
      - wekan
    environment:
      - BASE_URL=http://wekan:8080
    networks:
      - wekan-network

networks:
  wekan-network:
    driver: bridge

volumes:
  wekan-db:
  wekan-db-dump:
  wekan-storage:
