version: '3.8'

services:

  wekandb:
    image: mongo:6
    container_name: wekan-db
    restart: always
    command: mongod --logpath /dev/null --oplogSize 128 --quiet
    networks:
      - wekan-network
    expose:
      - 27017
    volumes:
      - wekan-db:/data/db
      - wekan-db-dump:/dump

  wekan:
    image: ghcr.io/wekan/wekan:latest
    container_name: wekan-app
    restart: always
    networks:
      - wekan-network
    depends_on:
      - wekandb
    ports:
      - "3000:3000"  # Changed from 8080 to match API usage
    environment:
      - MONGO_URL=mongodb://wekandb:27017/wekan
      - ROOT_URL=http://wekan:3000  # Use service name instead of localhost
      - WITH_API=true
    volumes:
      - wekan-files:/data:rw

  ai_sorting:
    build: .
    container_name: ai-cards-sort
    restart: always
    depends_on:
      - wekan
      - rabbitmq
    environment:
      - BASE_URL=http://wekan:3000  # Changed to service name instead of localhost
      - RABBITMQ_HOST=rabbitmq
    ports:
      - "5001:5001"
    networks:
      - wekan-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"  # RabbitMQ Management UI
    networks:
      - wekan-network

volumes:
  wekan-files:
    driver: local
  wekan-db:
    driver: local
  wekan-db-dump:
    driver: local

networks:
  wekan-network:
    driver: bridge
