version: '3.8'

services:

  wekandb:
    image: mongo:6
    container_name: wekan-db
    restart: always
    command: mongod --logpath /dev/null --oplogSize 128 --replSet rs0 --quiet
    networks:
      - wekan-network
    expose:
      - 27017
    volumes:
      - wekan-db:/data/db
      - wekan-db-dump:/dump

  wekandb-init:
    image: mongo:6
    container_name: wekan-db-init
    depends_on:
      - wekandb
    networks:
      - wekan-network
    restart: "no"
    entrypoint: [ "sh", "-c", "sleep 5 && mongosh --host wekandb --eval 'rs.initiate()'" ]

  wekan:
    image: adamray67/wekan-app
    container_name: wekan-app
    restart: always
    networks:
      - wekan-network
    depends_on:
      - wekandb
    ports:
      - "3000:8080"
    environment:
      - BASE_SORT_URL= "http://ai-cards-sort:5001"
      - MONGO_URL=mongodb://wekandb:27017/wekan
      - MONGO_OPLOG_URL=mongodb://wekandb:27017/local?replicaSet=rs0
      - WITH_API=true
    volumes:
      - /home/adamr/wekan_storage:/wekan_storage:rw

  ai_sorting:
    image: adamray67/ai-cards-sort:latest
    container_name: ai-cards-sort
    restart: always
    depends_on:
      - wekan
      - rabbitmq
    environment:
      - BASE_URL=http://wekan:8080
      - RABBITMQ_HOST=rabbitmq
    ports:
      - "5001:5001"
    networks:
      - wekan-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"  # RabbitMQ Management UI
    networks:
      - wekan-network

volumes:
  wekan-files:
    driver: local
  wekan-db:
    driver: local
  wekan-db-dump:
    driver: local

networks:
  wekan-network:
    driver: bridge
