name: 'Dependency Review'
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Fetches enough history to compare changes

      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          base-ref: main  # Compare against the main branch
          head-ref: ${{ github.ref_name }}  # Use the current pushed branch
