name: CI Pipeline for Integration env

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: read
  checks: write

jobs:

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull Test Container
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/wekan-tests:latest

      - name: Run Tests Inside the Container
        run: |
          docker run --rm \
            -e base_url=https://d17d-84-110-182-34.ngrok-free.app \
            ${{ secrets.DOCKER_USERNAME }}/wekan-tests:latest



  jmeter-tests:
    runs-on: ubuntu-latest
    needs: [integration-tests]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run JMeter Tests
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
          testFilePath: wekan_performance.jmx
          outputReportsFolder: reports/
          args: "--loglevel INFO"

      - name: Upload JMeter Test Results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-test-results
          path: reports/

  lighthouse-tests:
    runs-on: ubuntu-latest
    needs: [integration-tests]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Lighthouse CLI
        run: npm install -g lighthouse

      - name: Run Lighthouse Performance Audit
        run: |
          lighthouse https://5221-84-110-182-34.ngrok-free.app \
            --output=json \
            --output=html \
            --output-path=./lighthouse-report.html \
            --chrome-flags="--headless"

      - name: Upload Lighthouse Report
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: ./lighthouse-report.html



  build-and-push:
    runs-on: ubuntu-latest
    needs: [jmeter-tests]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build the Docker Image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/wekan-app:latest

      - name: Push the Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/wekan-app:latest
