name: Run Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout WeKan Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull Test Container
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/wekan-tests:latest

      - name: Run Tests Inside the Container
        run: |
          docker run --rm \
            -e base_url=https://d17d-84-110-182-34.ngrok-free.app \
            ${{ secrets.DOCKER_USERNAME }}/wekan-tests:latest
