name: Test suite

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read # to fetch code (actions/checkout)
#try
jobs:
# the following are optional jobs and need to be configured according
# to this project's settings:
#
#  lintcode:
#    name: Javascript lint
#    runs-on: ubuntu-latest
#    steps:
#    - name: checkout
#      uses: actions/checkout@v4
#
#    - name: setup node
#      uses: actions/setup-node@v1
#      with:
#        node-version: '12.x'
#
#    - name: cache dependencies
#      uses: actions/cache@v1
#      with:
#        path: ~/.npm
#        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
#        restore-keys: |
#          ${{ runner.os }}-node-
#
#    - run: npm install
#    - run: npm run lint:code
#
#  lintstyle:
#    name: SCSS lint
#    runs-on: ubuntu-latest
#    needs: [lintcode]
#    steps:
#    - name: checkout
#      uses: actions/checkout@v4
#
#    - name: setup node
#      uses: actions/setup-node@v1
#      with:
#        node-version: '12.x'
#
#    - name: cache dependencies
#      uses: actions/cache@v1
#      with:
#        path: ~/.npm
#        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
#        restore-keys: |
#          ${{ runner.os }}-node-
#    - run: npm install
#    - run: npm run lint:style
#
#  lintdocs:
#    name: documentation lint
#    runs-on: ubuntu-latest
#    needs: [lintcode,lintstyle]
#    steps:
#    - name: checkout
#      uses: actions/checkout@v4
#
#    - name: setup node
#      uses: actions/setup-node@v1
#      with:
#        node-version: '12.x'
#
#    - name: cache dependencies
#      uses: actions/cache@v1
#      with:
#        path: ~/.npm
#        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
#        restore-keys: |
#          ${{ runner.os }}-node-
#
#    - run: npm install
#    - run: npm run lint:markdown

  tests:
    name: Meteor Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Remove Old Meteor
        run: rm -rf ~/.meteor

      - name: Install Latest Meteor
        run: |
          curl https://install.meteor.com/ | sh
          export PATH="$HOME/.meteor:$PATH"
          meteor update --release 3.1.2
          meteor node -v  # Should output v20.x.x

      - name: Setup Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install NPM Dependencies
        run: |
          export METEOR_NODE_VERSION=20
          meteor npm ci

      - name: Run Tests
        run: |
          export METEOR_NODE_VERSION=20
          export PATH="$HOME/.meteor:$PATH"
          meteor node -v  # Verify correct version before running tests
          sh ./test-wekan.sh -cv

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-folder
          path: .coverage/


  coverage:
    name: Coverage report
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download coverage
        uses: actions/download-artifact@v4
        with:
          name: coverage-folder
          path: .coverage/


      - name: Coverage Report
        uses: VeryGoodOpenSource/very_good_coverage@v3.0.0
        with:
          path: ".coverage/lcov.info"
          min_coverage: 1 # TODO add tests and increase to 95!
