name: Test suite

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  tests:
    name: Meteor Tests (Node.js 20)
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Meteor 3.1.2
        run: |
          curl https://install.meteor.com/?release=3.1.2 | sh
          export PATH="$HOME/.meteor:$PATH"

      - name: Set Meteor Node.js to 20
        run: |
          export METEOR_NODE_VERSION=20
          meteor node -v  # Ensure correct version

      - name: Clean Meteor Cache
        run: |
          rm -rf ~/.meteor
          meteor reset

      - name: Install Dependencies
        run: meteor npm install

      - name: Run Tests
        run: sh ./test-wekan.sh -cv

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-folder
          path: .coverage/

  coverage:
    name: Coverage Report
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Coverage Data
        uses: actions/download-artifact@v4
        with:
          name: coverage-folder
          path: .coverage/

      - name: Generate Coverage Report
        uses: VeryGoodOpenSource/very_good_coverage@v3.0.0
        with:
          path: ".coverage/lcov.info"
          min_coverage: 1
