name: proj tests

on:
  pull_request:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build project
        run: echo "Building proj"

  TriggerDeployment:
    runs-on: ubuntu-latest
    needs: Build

    env:
      WEKAN_TSESTING_REPO_NAME: AdamRayann/WekanTesting
      UI_TESTING_WORKFLOW_ID: SmokeTesting.yaml
    steps:
      - name: Trigger the Selenium testing workflow
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"ref\": \"main\", \"inputs\": {\"grid_url\": \"http://localhost:4444\", \"chrome_131_0\": true}}" \
            https://api.github.com/repos/$SPOTIFY_TESTING_REPO_NAME/actions/workflows/$UI_TESTING_WORKFLOW_ID/dispatches
