name: Test suite

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  tests:
    name: Meteor ${{ matrix.meteor }} tests
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Upgrade Meteor to 3.1.2
        run: curl https://install.meteor.com/?release=3.1.2 | sh

      - name: Install Meteor
        id: cache-meteor-install
        uses: actions/cache@v4
        with:
          path: ~/.meteor
          key: v1-meteor-${{ hashFiles('.meteor/versions') }}
          restore-keys: |
                v1-meteor-

      - name: Cache NPM Dependencies
        id: cache-meteor-npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: v1-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
                v1-npm-

      - name: Cache Meteor Build
        id: cache-meteor-build
        uses: actions/cache@v4
        with:
          path: |
            .meteor/local/resolver-result-cache.json
            .meteor/local/plugin-cache
            .meteor/local/isopacks
            .meteor/local/bundler-cache/scanner
          key: v1-meteor_build_cache-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            v1-meteor_build_cache-

      - name: Set Correct Node.js Version for Meteor
        run: export METEOR_NODE_VERSION=20

      - name: Install Dependencies
        run: meteor npm install

      - name: Run Tests
        run: sh ./test-wekan.sh -cv

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-folder
          path: .coverage/

  coverage:
    name: Coverage Report
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Coverage Data
        uses: actions/download-artifact@v4
        with:
          name: coverage-folder
          path: .coverage/

      - name: Generate Coverage Report
        uses: VeryGoodOpenSource/very_good_coverage@v3.0.0
        with:
          path: ".coverage/lcov.info"
          min_coverage: 1  # TODO: Increase this as tests improve
