name: Wekan Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Meteor
        run: |
          curl https://install.meteor.com/ | sh
          echo "$HOME/.meteor" >> $GITHUB_PATH

      - name: Verify Meteor Installation
        run: meteor --version

      - name: Install Dependencies
        run: meteor npm install

      - name: Run Tests
        run: meteor npm test
