name: Wekan Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.18.1'

      - name: Install Meteor
        run: |
          curl https://install.meteor.com/ | sh
          echo "$HOME/.meteor" >> $GITHUB_PATH

      - name: Verify Meteor installation
        run: meteor --version

      - name: Set correct Node.js version for Meteor
        run: echo "export METEOR_NODE_VERSION=14.18.1" >> $GITHUB_ENV

      - name: Install dependencies
        run: meteor npm install

      - name: Reset Meteor environment
        run: meteor reset

      - name: Enable ES6+ support
        run: echo "NODE_OPTIONS=--harmony" >> $GITHUB_ENV

      - name: Run unit tests
        run: TEST_BROWSER_DRIVER=puppeteer meteor test --once --driver-package meteortesting:mocha
